name: test

on:
  push:
    branches: [  ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: stop server via ssh
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd project/git-action-test
          git pull origin master
          
    - name: public
      uses: appleboy/test@master
      with:  
        script: |
          cd project/git-action-test/public
          touch hello.txt
